//! Native tests for LZMA NCD.
//!
//! No frozen fixtures exist for this algorithm (see the behavior card and
//! the module doc-comment in `lzma_ncd.rs`). Reference values here were
//! generated by running the real, unmodified `textdistance.lzma_ncd`
//! locally (`docs/behavior-cards/manasa/lzma-ncd.md`), then confirmed to
//! match this Rust implementation's actual output exactly — `xz2`
//! (liblzma) produces byte-identical compressed output to Python's `lzma`
//! module for these cases.

use textdistance_port::algorithms::lzma_ncd::LzmaNcd;
use textdistance_port::{prepare_sequences, Algorithm, InputSequence, QValue};

fn distance(left: &str, right: &str) -> f64 {
    let sequences = prepare_sequences(
        &[
            InputSequence::Text(left.to_owned()),
            InputSequence::Text(right.to_owned()),
        ],
        QValue::Elements,
    )
    .expect("text preparation should succeed");
    LzmaNcd.distance(&sequences)
}

fn assert_close(actual: f64, expected: f64) {
    assert!(
        (actual - expected).abs() < 1e-9,
        "expected {expected}, got {actual}"
    );
}

#[test]
fn matches_python_generated_reference_values() {
    assert_close(distance("", ""), 0.0);
    assert_close(distance("test", "test"), 0.08695652173913043);
    assert_close(distance("test", "text"), 0.08695652173913043);
    assert_close(distance("test", "nani"), 0.08695652173913043);
    assert_close(distance("hello", "haloa"), 0.08);
}

#[test]
fn identical_and_similar_short_strings_collapse_to_the_same_score() {
    // Documented quirk from the behavior card: LZMA's fixed compression
    // overhead dominates at this input size, so "identical," "similar,"
    // and "different" are indistinguishable for very short strings. This
    // is faithful source behavior, not a bug — this test locks it in so a
    // future "fix" doesn't silently change the algorithm's behavior.
    assert_close(distance("test", "test"), distance("test", "text"));
    assert_close(distance("test", "text"), distance("test", "nani"));
}

#[test]
fn empty_empty_scores_zero() {
    assert_eq!(distance("", ""), 0.0);
}

#[test]
fn monotonicity_holds() {
    // The one property this algorithm's behavior card confirms even
    // without frozen fixtures: same <= similar <= different should still
    // hold, even though LZMA's overhead makes it a weak discriminator at
    // this input size (see identical_and_similar_short_strings_collapse...
    // above).
    let same = distance("test", "test");
    let similar = distance("test", "text");
    let different = distance("test", "nani");
    assert!(same <= similar, "{same} <= {similar}");
    assert!(similar <= different, "{similar} <= {different}");
}

#[test]
fn distance_is_symmetric() {
    assert_eq!(distance("hello", "haloa"), distance("haloa", "hello"));
}

#[test]
fn maximum_is_constant_one() {
    let sequences = prepare_sequences(
        &[
            InputSequence::Text("test".to_owned()),
            InputSequence::Text("nani".to_owned()),
        ],
        QValue::Elements,
    )
    .expect("text preparation should succeed");
    assert_eq!(LzmaNcd.maximum(&sequences), 1.0);
}

#[test]
fn fails_if_implementation_becomes_a_trivial_constant() {
    assert!(distance("hello", "haloa") != distance("test", "test"));
}
