//! Native tests for ZLIB NCD.
//!
//! No dedicated fixed-value test file exists in `tests/original/` for this
//! algorithm, but it is covered by
//! `tests/original/test_compression/test_common.py`'s shared property
//! tests. Reference values here were generated by running the real,
//! unmodified `textdistance.zlib_ncd` locally:
//! `docs/behavior-cards/manasa/zlib-ncd.md`.

use textdistance_port::algorithms::zlib_ncd::ZlibNcd;
use textdistance_port::{prepare_sequences, Algorithm, InputSequence, QValue};

fn distance(left: &str, right: &str) -> f64 {
    let sequences = prepare_sequences(
        &[
            InputSequence::Text(left.to_owned()),
            InputSequence::Text(right.to_owned()),
        ],
        QValue::Elements,
    )
    .expect("text preparation should succeed");
    ZlibNcd.distance(&sequences)
}

fn assert_close(actual: f64, expected: f64) {
    assert!(
        (actual - expected).abs() < 1e-9,
        "expected {expected}, got {actual}"
    );
}

#[test]
fn matches_python_generated_reference_values() {
    assert_close(distance("", ""), 0.0);
    assert_close(distance("test", "test"), 0.2);
    assert_close(distance("test", "text"), 0.4);
    assert_close(distance("test", "nani"), 0.4);
    assert_close(distance("hello", "haloa"), 0.45454545454545453);
}

#[test]
fn empty_empty_scores_zero() {
    assert_close(distance("", ""), 0.0);
}

#[test]
fn monotonicity_holds() {
    // Shared property from tests/original/test_compression/test_common.py.
    let same = distance("test", "test");
    let similar = distance("test", "text");
    let different = distance("test", "nani");
    assert!(same <= similar, "{same} <= {similar}");
    assert!(similar <= different, "{similar} <= {different}");
}

#[test]
fn distance_is_symmetric() {
    assert_close(distance("hello", "haloa"), distance("haloa", "hello"));
}

#[test]
fn maximum_is_constant_one() {
    let sequences = prepare_sequences(
        &[
            InputSequence::Text("test".to_owned()),
            InputSequence::Text("nani".to_owned()),
        ],
        QValue::Elements,
    )
    .expect("text preparation should succeed");
    assert_close(ZlibNcd.maximum(&sequences), 1.0);
}

#[test]
fn fails_if_implementation_becomes_a_trivial_constant() {
    assert!(distance("test", "test") != distance("test", "nani"));
}
